# >>> pip install pre-commit
# >>> pre-commit sample-config
# >>> pre-commit install

# (optional)
# >>> pre-commit run --all_files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: ["--line-length=88"]

  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.13.1
  #   hooks:
  #     - id: isort
  #       args: ["--profile=black"]
