name: Tests

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dioptra-io/publish-docker-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKE3070528e2de1N }}
          platforms: linux/amd64
          push: ${{ github.actor != 'dependabot[bot]' }}