name: Tests

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ecs-mapping-agent
          - score-agent
    steps:
      - uses: actions/checkout@v3
      - uses: dioptra-io/publish-docker-action@v1
        with:
          file: ./dockerfiles/${{ matrix.image }}.dockerfile
          image: dioptra-io/geogiant/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64
          push: ${{ github.actor != 'dependabot[bot]' }}

  main-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dioptra-io/publish-docker-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64
          push: ${{ github.actor != 'dependabot[bot]' }}